require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/estancias", type: :request do
  
  let(:user) { create(:user) }

  let(:valid_attributes) {
    build(:estancia).attributes
  }

  let(:invalid_attributes) {
    { nombre: '' }
  }

  let(:valid_headers) { authenticated_header(user) }

  describe "GET /index" do
    it "renders a successful response" do
      Estancia.create! valid_attributes
      get estancias_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      estancia = Estancia.create! valid_attributes
      get estancia_url(estancia), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Estancia" do
        expect {
          post estancias_url,
               params: { estancia: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Estancia, :count).by(1)
      end

      it "renders a JSON response with the new estancia" do
        post estancias_url,
             params: { estancia: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Estancia" do
        expect {
          post estancias_url,
               params: { estancia: invalid_attributes }, as: :json
        }.to change(Estancia, :count).by(0)
      end

      it "renders a JSON response with errors for the new estancia" do
        post estancias_url,
             params: { estancia: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { nombre: 'estancia2'}
      }

      it "updates the requested estancia" do
        estancia = Estancia.create! valid_attributes
        patch estancia_url(estancia),
              params: { estancia: new_attributes }, headers: valid_headers, as: :json
        estancia.reload
        expect(Estancia.last.nombre).to eq("estancia2")
      end

      it "renders a JSON response with the estancia" do
        estancia = Estancia.create! valid_attributes
        patch estancia_url(estancia),
              params: { estancia: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the estancia" do
        estancia = Estancia.create! valid_attributes
        patch estancia_url(estancia),
              params: { estancia: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested estancia" do
      estancia = Estancia.create! valid_attributes
      expect {
        delete estancia_url(estancia), headers: valid_headers, as: :json
      }.to change(Estancia, :count).by(-1)
    end
  end
end
