require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/lotes", type: :request do
  let(:user) { create(:user) }
  let(:file_png) { fixture_file_upload('sample_file.png', 'image/png') }
  let(:file_jpg) { fixture_file_upload('sample_file.jpg', 'image/jpg') }

  let(:estancia) { create(:estancia) }

  let(:valid_attributes) {
    { estancia_id: estancia.id, nombre: '8', adjuntos: [ file_png ] }
  }

  let(:invalid_attributes) {
    { nombre: nil }
  }

  let(:valid_headers) { authenticated_header(user) }

  let(:full_show_keys) { LoteSerializer::FULL_SHOW_KEYS }

  describe "GET /index" do
    it "renders a successful response" do
      Lote.create! valid_attributes
      get lotes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      lote = Lote.create! valid_attributes
      get lote_url(lote), headers: valid_headers, as: :json
      expect(response).to be_successful
    end

    it "renders the correct keys" do
      lote = Lote.create! valid_attributes
      get lote_url(lote), headers: valid_headers, as: :json
      expect(json_response.keys).to match_array(full_show_keys)
    end

    it "shows attached files in the response" do
      lote = Lote.create! valid_attributes
      get lote_url(lote), headers: valid_headers, as: :json
      expect(json_response["adjuntos"]).not_to be_empty
    end
  end

  describe "GET /lotes/:id/adjuntos" do
    it "returns only lote adjuntos" do
      lote = Lote.create! valid_attributes

      get adjuntos_lote_url(lote), headers: valid_headers, as: :json

      expect(response).to have_http_status(:ok)
      expect(json_response).to be_an(Array)
      expect(json_response.size).to eq(1)
      expect(json_response.first.keys).to match_array(%w[id filename content_type url])
      expect(json_response.first["filename"]).to eq("sample_file.png")
    end

    it "returns 404 if lote not found" do
      get adjuntos_lote_url(99999), headers: valid_headers, as: :json

      expect(response).to have_http_status(:not_found)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Lote" do
        expect {
          post lotes_url,
               params: { lote: valid_attributes }, headers: valid_headers
        }.to change(Lote, :count).by(1)
      end

      it "adjunta la imagen" do
        post lotes_url,
             params: { lote: valid_attributes }, headers: valid_headers
        expect(Lote.last.adjuntos.count).to eq(1)
        expect(json_response["adjuntos"]).not_to be_empty
      end

      it "renders a JSON response with the new lote" do
        post lotes_url,
             params: { lote: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Lote" do
        expect {
          post lotes_url,
               params: { lote: invalid_attributes }
        }.to change(Lote, :count).by(0)
      end

      it "renders a JSON response with errors for the new lote" do
        post lotes_url,
             params: { lote: invalid_attributes }, headers: valid_headers
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { nombre: '9', adjuntos: [ file_jpg ] }
      }

      it "updates the requested lote" do
        lote = Lote.create! valid_attributes
        patch lote_url(lote),
              params: { lote: new_attributes }, headers: valid_headers
        lote.reload
        expect(Lote.last.nombre).to eq('9')
        expect(Lote.last.adjuntos.count).to eq(2)
        expect(json_response["adjuntos"]).not_to be_empty
        expect(json_response["adjuntos"].map { |a| a["filename"] }).to match_array([ "sample_file.png", "sample_file.jpg" ])
      end

      it "renders a JSON response with the lote" do
        lote = Lote.create! valid_attributes
        patch lote_url(lote),
              params: { lote: new_attributes }, headers: valid_headers
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the lote" do
        lote = Lote.create! valid_attributes
        patch lote_url(lote),
              params: { lote: invalid_attributes }, headers: valid_headers
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested lote" do
      lote = Lote.create! valid_attributes
      expect {
        delete lote_url(lote), headers: valid_headers, as: :json
      }.to change(Lote, :count).by(-1)
    end
  end
end
